version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - automerge
  allow:
  - dependency-name: "@ecomplus/storefront-template"
  ignore:
  - dependency-name: "@ecomplus/storefront-template"
    versions:
    - 2.0.0-beta.111
    - 2.0.0-beta.112
    - 2.0.0-beta.113
    - 2.0.0-beta.114
    - 2.0.0-beta.115
    - 2.0.0-beta.116
    - 2.0.0-beta.117
    - 2.0.0-beta.120
  commit-message:
    prefix: fix
    include: scope
- package-ecosystem: npm
  directory: "/.netlify/functions/ssr"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - automerge
  allow:
  - dependency-name: "@ecomplus/storefront-renderer"
  ignore:
  - dependency-name: "@ecomplus/storefront-renderer"
    versions:
    - 2.4.12
    - 2.4.13
    - 2.4.14
    - 2.4.15
    - 2.5.0
    - 2.6.0
    - 2.7.0
  commit-message:
    prefix: chore
    include: scope
